### PR TITLE
fix(bip39): redact Mnemonic::Debug

### LINKED ISSUE #92: Consider obscuring seed from Debug implementation of Mnemonic
Its a common footgun that secrets get leaked in log messages when types containing private secrets implement Debug, whose implementation actually prints the secret.

bip39 should instead do something like:

```rust
impl fmt::Debug for Mnemonic {
	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
		f.debug_struct("Mnemonic")
			.field("lang", &self.0.language())
			.finish_non_exhaustive()
	}
}
```

### PR DESCRIPTION
**Pull request by caarloshenriq**
- Implement manual fmt::Debug using `finish_non_exhaustive()`  #92
- Hide mnemonic phrase/indices; show only `lang`
- Add test ensuring `{:?}` never contains mnemonic words

### CODE REVIEW

**Review by tnull — APPROVED** [review]
LGTM

Makes sense, IMO.

File: src/lib.rs [hunk 1]
```diff
@@ -655,6 +655,14 @@ impl fmt::Display for Mnemonic {
 	}
 }
 
+impl fmt::Debug for Mnemonic {
+	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+		f.debug_struct("Mnemonic")
+			.field("lang", &self.language())
+			.finish_non_exhaustive()
```
Comment (tnull) [inline src/lib.rs]: Ah, unfortunately this is only available since rustc 1.53 (see https://doc.rust-lang.org/std/fmt/struct.DebugStruct.html#method.finish_non_exhaustive). Given that we currently still support 1.41, we should probably just use `finish` for the time being (preferably leaving a TODO comment to switch to `finish_non_exhaustive` once we drop that MSRV requirement.

Comment (caarloshenriq) [reply src/lib.rs]: Thanks for the review. I change to `.finish()` and added a TODO to migrate to `finish_non_exhaustive()` when we bump MSRV

**Review by tnull — COMMENTED** [review]
LGTM, please squash commits and provide a proper commit message (briefly) describing what you did, why it was necessary, and which approach you took.

For guidance on how to write good commit messages, see for example https://cbea.ms/git-commit/

File: src/lib.rs [hunk 2]
```diff
@@ -1005,6 +1014,25 @@ mod tests {
 		assert_eq!(Mnemonic::from_entropy(&vec![b'x'; 36]), Err(Error::BadEntropyBitCount(288)));
 	}
 
+	#[test]
+	fn debug_does_not_leak_phrase() {
+		let m = Mnemonic::from_entropy(&[0u8; 16]).unwrap();
+
+		let dbg = format!("{:?}", m);
+
+		assert!(dbg.starts_with("Mnemonic {") || dbg.starts_with("Mnemonic(") || dbg.contains("Mnemonic"),
```
Comment (elsirion) [inline src/lib.rs:1023]: nit: redundant cases: the last `contains` will match anything the previous cases match.

**Review by elsirion — APPROVED** [review]

File: src/lib.rs (hunk 2 above)
Comment (tnull) [reply src/lib.rs:1023]: True, although no need to hold this PR just for this, IMO.

**Review by tnull — APPROVED** [review]
